<?php
require("./headerLoup.php");
?>

<p>Séquences 1 et 2 soumises au logiciel d'alignement : </p>
<p class='Z'>>Séquence 1</p>
<p><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span> <span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span></p>
<p class='Z'>>Séquence 2</p>
<p><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span></p>

<p>Séquences 1 et 2 alignées : le meilleur score est de <b>57</b>.</p>
<p>Un score supérieur à 40 est obtenu en ajoutant des décalages dans la séquence. Ils sont notés ici via un point '<span class="z">.</span>'.</p>

<img src="./EcoleADN/interface1.png" alt = "">

<p><span class="z">.............</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="z">.</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="z">.</span><span class="z">.</span><span class="z">.</span><span class="z">.</span><span class="z">.</span><span class="z">.</span></p>
<p class="z">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|||||||||||||&nbsp;|||||||||||||||||||||||||||||||||||&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||||||||</p>
<p><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="z">.</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span></p>
<img src="./EcoleADN/interface2.png" alt = "">


<p>Les outils bioinformatiques permettent de trouver LE meilleur alignement... et donc LE meilleur score !</p>


<p>Maintenant que tu as tout compris tu peux continuer l'enquête.</p>
<p><a class="btn btn-outline-primary btn-lg" role="button" href= "./Enquete.php?q=0">Continuer</a></p>

<?php
require("./footerLoup.php");
?>
