<?php
require("./headerLoup.php");
?>
<p>Le bioinformaticien développe et/ou utilise des outils
informatiques complexes utiles aux problématiques biologiques.</p>

<p>Pour trouver LE meilleur alignement, il suffit d'un clic sur le bouton "soumettre".</p>
<img src="./EcoleADN/interface1.png" alt = "">
<p class='Z'>>Séquence 1</p>
<p><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span> <span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span></p>
<p class='z'>>Séquence 2</p>
<p><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="c">C</span><span class="g">G</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="t">T</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="c">C</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="c">C</span><span class="a">A</span><span class="c">C</span><span class="g">G</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="g">G</span><span class="a">A</span><span class="a">A</span><span class="t">T</span><span class="a">A</span></p>

<p><a class="btn btn-outline-primary btn-lg" role="button" href= "./Interface.php">Soumettre</a></p>
<img src="./EcoleADN/interface3.png" alt = "">

<?php
require("./footerLoup.php");
?>
